### ISSUE TITLE
Tag Releases

### ISSUE THREAD

**Issue by osxi** [luizstacio/json-format#2]
It would probably be helpful if you tagged releases for this here on GitHub so those coming from NPM can more-easily understand what's going on with different versions.

**Comment by luizstacio** [comment]
Sorry, I was wrong not to have done this, I will create a list of releases, to describe the changes. I just wrote the new features in the README.

Thanks.

**Comment by luizstacio** [comment]
https://github.com/luizstacio/json-format/releases/tag/v0.1.1
